name: CI/CD FOR DEV DEPLOY

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          run: heroku container:login
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "java-ci-cd-actions"
          heroku_email: "moises1695@gmail.com"
          buildpack: "https://git.heroku.com/java-ci-cd-actions.git"
